// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0enNIomPglOuP1fSO3PlDFS3d47GIQRM',
    appId: '1:173874248891:web:1c30debad80abebcf47d9e',
    messagingSenderId: '173874248891',
    projectId: 'cloudmessaging-92a4b',
    authDomain: 'cloudmessaging-92a4b.firebaseapp.com',
    storageBucket: 'cloudmessaging-92a4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7GXgwrgXBITf7hpT1s4ARgJvb_Pgc1-c',
    appId: '1:173874248891:android:9adfbd233181536ff47d9e',
    messagingSenderId: '173874248891',
    projectId: 'cloudmessaging-92a4b',
    storageBucket: 'cloudmessaging-92a4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxuOXvwHcy3Ep92nDlLwdada82QwUJ9-M',
    appId: '1:173874248891:ios:4430eb964138817cf47d9e',
    messagingSenderId: '173874248891',
    projectId: 'cloudmessaging-92a4b',
    storageBucket: 'cloudmessaging-92a4b.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxuOXvwHcy3Ep92nDlLwdada82QwUJ9-M',
    appId: '1:173874248891:ios:4430eb964138817cf47d9e',
    messagingSenderId: '173874248891',
    projectId: 'cloudmessaging-92a4b',
    storageBucket: 'cloudmessaging-92a4b.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0enNIomPglOuP1fSO3PlDFS3d47GIQRM',
    appId: '1:173874248891:web:a8d39ff5a53e6483f47d9e',
    messagingSenderId: '173874248891',
    projectId: 'cloudmessaging-92a4b',
    authDomain: 'cloudmessaging-92a4b.firebaseapp.com',
    storageBucket: 'cloudmessaging-92a4b.firebasestorage.app',
  );
}
